# Generated by Django 5.2.8 on 2026-07-03 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usertask',
            old_name='complete',
            new_name='completed',
        ),
        migrations.RenameField(
            model_name='usertask',
            old_name='time',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='usertask',
            name='user',
        ),
        migrations.AddField(
            model_name='usertask',
            name='category',
            field=models.CharField(choices=[('Work', 'Work'), ('Personal', 'Personal'), ('College', 'College')], default='Personal', max_length=20),
        ),
        migrations.AddField(
            model_name='usertask',
            name='priority',
            field=models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], default='Low', max_length=10),
        ),
        migrations.AlterField(
            model_name='usertask',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
