# Generated by Django 5.2.8 on 2026-07-03 10:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_usertask_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='usertask',
            old_name='completed',
            new_name='complete',
        ),
        migrations.RenameField(
            model_name='usertask',
            old_name='created_at',
            new_name='time',
        ),
        migrations.RemoveField(
            model_name='usertask',
            name='category',
        ),
        migrations.RemoveField(
            model_name='usertask',
            name='priority',
        ),
        migrations.AlterField(
            model_name='usertask',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='usertask',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
